Algoritmo "Exercício 11"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("informe sua nota:")
leia(media)
se (media>= 7)entao
escreva("aluno aporvado")

senao
escreva("aluno reprovado")

fimse

Fimalgoritmo