Algoritmo "Exercício 1"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
 nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite seu nome: ", nome)
leia(nome)
escreva("Olá ", nome, " seja bem vindo!")

Fimalgoritmo