Algoritmo "Exercício 3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
num1, num2, n1: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ",n1)
leia(n1)
num1 <- n1 + 1

num2<- n1 - 1
escreva(num1)
escreva(num2)
Fimalgoritmo