Algoritmo "Exercício 9 PM"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe um número: ")
leia(num)
se (num mod 2 = 0)entao
escreva("Seu numero é par")

senao
escreva("seu numero é impar")

fimse
Fimalgoritmo