Algoritmo "Exercício 5"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
idade, meses, dias: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite sua idade em anos:")
leia(idade)
dias <- idade * 12
meses <- idade * 365
escreva("Sua idade em meses", meses, " e dias em dias é: ", dias)
Fimalgoritmo