Algoritmo "Exercício 2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
soma, n1, n2: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o primeiro número: ", n1)
leia(n1)
escreva("Digite o segundo número: ", n2)
leia(n2)

soma <- n1 + n2

escreva("Resultado da soma: ", soma)

Fimalgoritmo