Algoritmo "Exercício 4"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
base, altura, area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("informe a base:")
leia(base)
escreva("informe a altura:")
leia(altura)
area <- base * altura
escreva("sua area é:", area)
Fimalgoritmo