Algoritmo "Exercício 7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
num: inteiro
resto: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe um número: ")
leia(num)
resto <- num mod 2
escreva("o resto da divisão é: ", resto)


Fimalgoritmo